# Generated by Django 5.1.4 on 2025-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='check_choice',
            field=models.BooleanField(default=False),
        ),
    ]
